### ISSUE TITLE
Вопрос: Ошибка подключения modbus в ha

### ISSUE THREAD

**Issue by enkorsh** [klim123123/neptun_smart_homeassistant#5]
Здравствуйте!

Пытаюсь подключится к своему устройству Neptun Smart+ из HA через modbus tcp

В результате получаю ошибку

Регистратор: pymodbus.logging
Источник: components/modbus/modbus.py:313
Первое сообщение: 17:57:49 (1 сообщений)
Последнее сообщение: 17:57:49

Failed to connect [Errno 111] Connect call failed ('192.168.1.200', 503)

Что я делаю не так?
Устройство подключено в Tuya Smart, ограничение на блокировку выхода в интернет не устанавливал, т.к. у вас написано нет необходимости.
Модуль modbus в Neptun не установлен

Заранее спасибо!

**Comment by enkorsh** [comment]
Извините, так вроде бы адрес его и есть, или как-то
 по другому нужно узнавать, докупать модуль расширения Ethernet?

![2024-11-15_18-08-55](https://github.com/user-attachments/assets/bbb4af6d-32bf-4e54-b743-f9fd649c5e1a)

**Comment by klim123123** [comment]
Судя по хосту это всетаки Tuya модуль коннектится.
Нужно отключить модуль Tuya и подключить Нептун его wifi в любой сервис(sst или atlas), потом вернуть модуль туя на место(если он вообще нужен теперь). У вас будет подключено два устройства теперь.

**Comment by enkorsh** [comment]
Спасибо!

**Comment by klim123123** [comment]
Дайте знать как все получилось. Я напишу информацию для других пользователей.

**Comment by enkorsh** [comment]
Я завтра отпишусь, ближе к вечеру
